apiVersion: v1
kind: Service
metadata:
  name: analytics
  namespace: platform
  labels:
    app.kubernetes.io/name: analytics
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: analytics
  ports:
    - name: http
      port: 9512
      targetPort: 9512
      protocol: TCP
