apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: platform
  labels:
    app.kubernetes.io/name: orchestrator
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: orchestrator
  ports:
    - name: http
      port: 9501
      targetPort: 9501
      protocol: TCP
