/**
 * HallucinationWarning — AI Confidence Disclaimer
 *
 * Communicates to users when AI-generated content may not be reliable.
 * Severity levels trigger different visual urgency cues.
 *
 * Variants:
 * - inline: Compact, sits within text flow
 * - banner: Full-width, prominent display
 *
 * Severities: info, caution, warning, critical
 */

import { motion } from 'framer-motion';
import {
  Info,
  AlertTriangle,
  ShieldAlert,
  OctagonAlert,
  ExternalLink,
} from 'lucide-react';
import { cn } from '../../../utils';

// ============================================================================
// Types
// ============================================================================

export type HallucinationSeverity = 'info' | 'caution' | 'warning' | 'critical';

export interface HallucinationWarningProps {
  /** Severity of the hallucination risk */
  severity: HallucinationSeverity;
  /** Primary warning message */
  message?: string;
  /** Specific claims flagged as potentially hallucinated */
  flaggedClaims?: string[];
  /** Action button label (e.g. "Verify Sources") */
  actionLabel?: string;
  /** Action callback */
  onAction?: () => void;
  /** Variant */
  variant?: 'inline' | 'banner';
  /** Additional CSS classes */
  className?: string;
}

// ============================================================================
// Config
// ============================================================================

const severityConfig: Record<HallucinationSeverity, {
  icon: typeof Info;
  color: string;
  bgColor: string;
  borderColor: string;
  label: string;
  defaultMessage: string;
}> = {
  info: {
    icon: Info,
    color: 'var(--primary)',
    bgColor: 'color-mix(in srgb, var(--primary) 6%, transparent)',
    borderColor: 'color-mix(in srgb, var(--primary) 20%, var(--border))',
    label: 'AI Generated',
    defaultMessage: 'This response was generated by AI. Verify important details independently.',
  },
  caution: {
    icon: AlertTriangle,
    color: 'var(--warning, #d97706)',
    bgColor: 'color-mix(in srgb, var(--warning, #d97706) 8%, transparent)',
    borderColor: 'color-mix(in srgb, var(--warning, #d97706) 25%, var(--border))',
    label: 'Caution',
    defaultMessage: 'Some details in this response may not be fully accurate. Cross-reference before acting.',
  },
  warning: {
    icon: ShieldAlert,
    color: 'var(--destructive)',
    bgColor: 'color-mix(in srgb, var(--destructive) 8%, transparent)',
    borderColor: 'color-mix(in srgb, var(--destructive) 25%, var(--border))',
    label: 'Low Confidence',
    defaultMessage: 'The AI has low confidence in parts of this response. Please verify all claims.',
  },
  critical: {
    icon: OctagonAlert,
    color: 'var(--destructive)',
    bgColor: 'color-mix(in srgb, var(--destructive) 12%, transparent)',
    borderColor: 'color-mix(in srgb, var(--destructive) 40%, var(--border))',
    label: 'Hallucination Risk',
    defaultMessage: 'This response contains claims that could not be verified. Do not rely on this without independent confirmation.',
  },
};

// ============================================================================
// Component
// ============================================================================

export function HallucinationWarning({
  severity,
  message,
  flaggedClaims,
  actionLabel = 'Verify Sources',
  onAction,
  variant = 'banner',
  className,
}: HallucinationWarningProps) {
  const config = severityConfig[severity];
  const Icon = config.icon;
  const displayMessage = message || config.defaultMessage;
  const isCritical = severity === 'critical';

  if (variant === 'inline') {
    return (
      <span
        className={cn(
          'inline-flex items-center gap-1 rounded-md px-1.5 py-0.5 text-[11px] font-medium',
          className
        )}
        style={{
          background: config.bgColor,
          color: config.color,
          border: `1px solid ${config.borderColor}`,
        }}
        data-component="HallucinationWarning"
      >
        <Icon className="h-3 w-3 shrink-0" />
        <span>{config.label}</span>
      </span>
    );
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      className={cn('rounded-xl overflow-hidden relative glass-card', className)}
      style={{
        background: config.bgColor,
        border: `1px solid ${config.borderColor}`,
      }}
      role={isCritical ? 'alert' : 'status'}
      aria-label={`${config.label}: ${displayMessage}`}
      data-component="HallucinationWarning"
    >
      {/* Premium Hazard Striping for Critical Hallucinations */}
      {isCritical && (
        <motion.div
          className="absolute inset-0 pointer-events-none opacity-20"
          style={{
            backgroundImage: `repeating-linear-gradient(
              -45deg,
              transparent,
              transparent 10px,
              color-mix(in srgb, ${config.color} 50%, transparent) 10px,
              color-mix(in srgb, ${config.color} 50%, transparent) 20px
            )`,
            backgroundSize: '28.28px 28.28px',
          }}
          animate={{ backgroundPosition: ['0px 0px', '28.28px 28.28px'] }}
          transition={{ repeat: Infinity, ease: 'linear', duration: 2 }}
        />
      )}

      {/* Subtle Critical Glow */}
      {isCritical && (
        <div
          className="absolute inset-0 pointer-events-none rounded-xl"
          style={{ boxShadow: `inset 0 0 20px color-mix(in srgb, ${config.color} 15%, transparent)` }}
        />
      )}

      <div className="flex items-start gap-3 p-3 relative z-10">
        {/* Icon with optional pulse */}
        <div className="relative shrink-0 mt-0.5">
          {isCritical && (
            <motion.div
              className="absolute inset-0 rounded-full"
              style={{ background: config.color }}
              animate={{ scale: [1, 1.8, 1], opacity: [0.3, 0, 0.3] }}
              transition={{ duration: 2, repeat: Infinity }}
            />
          )}
          <div
            className="relative flex items-center justify-center w-7 h-7 rounded-full"
            style={{
              background: `color-mix(in srgb, ${config.color} 15%, transparent)`,
            }}
          >
            <Icon className="h-3.5 w-3.5" style={{ color: config.color }} />
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-0.5">
            <span
              className="text-xs font-bold uppercase tracking-wider"
              style={{ color: config.color }}
            >
              {config.label}
            </span>
          </div>
          <p
            className="text-xs leading-relaxed"
            style={{ color: 'var(--foreground)' }}
          >
            {displayMessage}
          </p>

          {/* Flagged claims */}
          {flaggedClaims && flaggedClaims.length > 0 && (
            <div className="mt-2 space-y-1">
              {flaggedClaims.map((claim, i) => (
                <div
                  key={i}
                  className="flex items-start gap-1.5 text-[11px] rounded-md px-2 py-1"
                  style={{
                    background: `color-mix(in srgb, ${config.color} 8%, transparent)`,
                    color: 'var(--foreground)',
                  }}
                >
                  <AlertTriangle
                    className="h-3 w-3 shrink-0 mt-0.5"
                    style={{ color: config.color }}
                  />
                  <span className="italic">&ldquo;{claim}&rdquo;</span>
                </div>
              ))}
            </div>
          )}

          {/* Action */}
          {onAction && (
            <button
              type="button"
              onClick={onAction}
              className="mt-2 inline-flex items-center gap-1 rounded-md px-2 py-1 text-[11px] font-semibold transition-colors"
              style={{
                color: config.color,
                background: `color-mix(in srgb, ${config.color} 10%, transparent)`,
                border: `1px solid color-mix(in srgb, ${config.color} 25%, transparent)`,
              }}
            >
              <ExternalLink className="h-3 w-3" />
              {actionLabel}
            </button>
          )}
        </div>
      </div>
    </motion.div>
  );
}

HallucinationWarning.displayName = 'HallucinationWarning';

export default HallucinationWarning;
